### ISSUE TITLE
Aruba connect fails

### ISSUE THREAD

**Issue by gkalthof** [miken32/rancid-aruba#4]
bin/rancid -t aruba 10.10.50.152 -d -V
10.10.50.152: End of run not found

I'm willing to debug the session

**Comment by jrbinks** [comment]
What model of device are you testing with?

**Comment by gkalthof** [comment]
Hi JR,
I'm testing with an Aruba R0X24A. 
I've been using the aruba module, whcih did not work.

Meanwhile I found a module arubaoscx
 arubaoscx.pm - Base rancid procedures
# Contributed by J R Binks <jethro.binks@strath.ac.uk>

which was obviously made by you, but I can't find the official sources and manual.

This module works fine.

Can you give me a hint what the aruba mdule is being used for and where I can find the officical download for arubaoscx!

I appreciate your ecellent work
Yours

Gerald

**Comment by jrbinks** [comment]
Yeah this module from @miken32 won't work for that, you need something with AOS-CX support.  I guess you found the initial gist I did with some basic support at https://gist.github.com/jrbinks/c28691f11238c23432394302a948900b, I should make a proper repo and upload the current version.  Will note here if/when I do.

**Comment by gkalthof** [comment]
Hi Jethro,

Would be great, it it was easieer to find! Thanks a lot for your help!

Gerald

**Comment by jrbinks** [comment]
I forgot to say @gkalthof, I did a bit more on this and it is here: https://github.com/jrbinks/rancid-arubaoscx
