### ISSUE TITLE
Aruba config doesn't include spaces at the front any more

### ISSUE THREAD

**Issue by trs80** [miken32/rancid-aruba#6]
I upgraded from ArubaOS 8.7 to 8.10 and none of the encrypted passwords got removed any more. Inspecting the output, it's because `write term` doesn't include any indentation spaces, so the regexes need to be changed from `/^(\s+wpa-passphrase )/` to `/^(\s?wpa-passphrase )/` (ie `+` to `?`).

As a bonus, most (but not all!) lines contain a space at the end which ruins diffing from previous configs, where only some lines had terminal spaces before. So in WriteTerm I put this at top of the `while (<$INPUT>) {` loop
```perl
        # strip trailing whitespace
        s/ $//;
```

**Comment by trs80** [comment]
Of course it should be `*` not `?`, as indicated by the fact that vrrp-id is still indented and got missed :facepalm:

**Comment by trs80** [comment]
and 
```perl
        # strip trailing whitespace
        s/\s+$//;
```
because some lines have multiple terminal spaces like deny-needfrag-df-ipsec in wireless-bridge-aging

**Comment by miken32** [comment]
Thanks, so basically every output line just needs whitespace to be trimmed before processing?

Would you mind doing a pull request for those changes? If not I can get to it, just might be a bit.

And can you confirm it doesn’t cause problems with older firmware? I no longer use Aruba gear, so I have no way to test.

**Comment by trs80** [comment]
Pull request sent. Due to debugging I've tested this on 8.7, 8.8, 8.9 and 8.10 and it works fine. Existing users will have a big spurious diff due to stripping trailing whitespace.
